apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoreact
          image: gkapps.azurecr.io/todo-react:latest
          ports:
            - containerPort: 3000
        - name: todoservice
          image: gkapps.azurecr.io/todo-service:latest
          ports:
            - containerPort: 5070
          env:
            - name: MONGO_CONNECTION_STRING
              value: ${MONGO_CONNECTION_STRING}
      restartPolicy: Always
