apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
  type: LoadBalancer