apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
    - port: 80
      name: reactport
      targetPort: 3000
    - port: 5070
      name: serviceport
      targetPort: 5070
