FROM node:14.17.3-alpine3.14 as builder
LABEL author=gaurav.intouch@gmail.com
WORKDIR /usr/todoservice-build
COPY . .
RUN npm install typescript -g
RUN npm install
RUN npm run build
FROM node:14.17.3-alpine3.14
COPY --from=builder /usr/todoservice-build/dist /usr/todoservice
COPY --from=builder /usr/todoservice-build/node_modules /usr/todoservice/node_modules
WORKDIR /usr/todoservice
EXPOSE 5070
ENTRYPOINT ["node", "index.js"]
